apiVersion: apps/v1
kind: Deployment
metadata:
 name: simple-deployment
 labels:
   app: simple-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: simple-app
 template:
   metadata:
     labels:
       app: simple-app
   spec:
     containers:
     - name: simple-app-cont
       image: docker.io/xrlim/simple-app:latest
       ports:
        - containerPort: 8080       
        