apiVersion: v1
kind: Service
metadata:
 name: simple-service
 labels:
   app: simple-app
spec:
 selector:
   app: simple-app
 type: ClusterIP
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080